import assert from "node:assert/strict";
import { chromium } from "playwright";

const base = process.env.BASE_URL || "http://127.0.0.1:3000";
const browser = await chromium.launch({ channel: "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(base);
  assert(await page.locator(".intro-retro-screen").isVisible());
  const fillsViewport = () => page.locator(".intro-retro-screen").evaluate(screen => {
    const bounds = screen.getBoundingClientRect();
    return bounds.left <= 20 && bounds.top <= 20 && bounds.right >= innerWidth - 20 && bounds.bottom >= innerHeight - 20;
  });
  assert(await fillsViewport(), "Desktop CRT should fill the viewport");
  assert(await page.evaluate(() => document.querySelector(".intro-retro-skip").getBoundingClientRect().bottom < document.querySelector(".intro-retro-bottom").getBoundingClientRect().top), "Desktop Skip should clear the status line");
  assert((await page.locator(".intro-retro-name").textContent()).includes("Adnan"));
  await page.waitForFunction(() => ["done", "skip"].includes(document.querySelector(".intro")?.getAttribute("data-state")), { timeout: 7000 });
  await page.locator(".intro").waitFor({ state: "hidden" });
  assert.equal(await page.locator("h1").count(), 1);
  assert.equal(await page.locator("html").getAttribute("lang"), "en");
  assert.equal(await page.locator(".language-toggle").count(), 0);
  assert.equal(await page.locator(".live-world canvas").count(), 1);
  assert.equal(await page.locator(".live-world").getAttribute("data-chapter"), "home");
  assert.equal(await page.locator("#home .command-action").count(), 0);
  assert(await page.locator(".hero-terminal").isVisible());
  assert(await page.evaluate(() => document.querySelector(".hero-coordinate").getBoundingClientRect().top > document.querySelector(".hero-terminal").getBoundingClientRect().bottom));
  await page.locator(".terminal-secret").click();
  assert(await page.getByRole("dialog", { name: "AN/OS terminal" }).isVisible());
  await page.locator("#terminal-input").fill("cat cv.json");
  await page.locator("#terminal-input").press("Enter");
  assert((await page.locator(".terminal-window-screen").textContent()).includes("Ain Shams University"));
  await page.locator("#terminal-input").press("ArrowUp");
  assert.equal(await page.locator("#terminal-input").inputValue(), "cat cv.json");
  await page.waitForTimeout(1200);
  assert.equal(await page.evaluate(() => document.activeElement?.id), "terminal-input", "Session clock must not steal terminal focus");
  await page.locator("#terminal-input").press("Escape");
  assert.equal(await page.getByRole("dialog", { name: "AN/OS terminal" }).count(), 0);
  assert.equal(await page.locator(".timeline-rail a").count(), 6);
  assert.equal(await page.locator("#codex").count(), 1);
  assert.equal(await page.locator("a[href*='kanz-ai']").count(), 0);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  const enterChapter = async id => {
    await page.evaluate(id => {
      const section = document.getElementById(id);
      scrollTo({ top: section.getBoundingClientRect().top + scrollY - innerHeight * 0.18, behavior: "instant" });
    }, id);
    await page.waitForFunction(id => document.querySelector(".live-world")?.getAttribute("data-chapter") === id, id, { timeout: 3000 });
  };
  await enterChapter("now");
  await page.locator(".site-nav.nav-scrolled").waitFor({ state: "attached" });
  await page.evaluate(() => scrollBy({ top: -180, behavior: "instant" }));
  await page.locator(".site-nav.nav-scrolled:not(.nav-hidden)").waitFor({ state: "attached" });
  assert(await page.locator(".site-nav").evaluate(element => getComputedStyle(element).backdropFilter !== "none"));
  await enterChapter("work");
  await enterChapter("now");
  assert.equal(await page.locator(".now-v2-energy-bar").getAttribute("aria-valuenow"), "70");
  assert.equal(await page.locator(".now-v2-node").count(), 6);
  await page.locator(".now-v2-node").nth(4).click();
  assert.equal(await page.locator(".now-v2-node").nth(4).getAttribute("aria-expanded"), "true");
  assert((await page.locator(".now-v2-readout").textContent()).includes("AI agents"));
  assert.equal(await page.locator(".now-v2-readout").count(), 1);
  await page.locator(".codex-console").scrollIntoViewIfNeeded();
  await page.locator("#codex.is-live").waitFor({ state: "attached", timeout: 3000 });
  await page.waitForFunction(() => document.querySelectorAll(".codex-menu button")[1]?.classList.contains("is-selected"), null, { timeout: 6500 });
  await page.locator(".codex-menu button").nth(1).click();
  assert.equal(await page.locator(".codex-menu button").nth(1).getAttribute("aria-pressed"), "true");
  assert((await page.locator(".codex-detail-copy").textContent()).includes("useful software"));
  await page.locator("#about").scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  assert.equal(await page.locator(".story-panel").count(), 4);
  assert.equal(await page.locator(".story-code-field span").count(), 24);
  assert.equal(await page.locator(".story-controls").count(), 0);
  assert.equal(await page.locator(".story-panel.is-active").count(), 1);
  await page.evaluate(() => { const track = document.querySelector(".story-track"); const top = track.getBoundingClientRect().top + scrollY; scrollTo({ top: top + (track.offsetHeight - innerHeight) * 0.55, behavior: "instant" }); });
  await page.waitForFunction(() => document.querySelector(".story-panel.is-active")?.textContent?.includes("Adnan OS"), null, { timeout: 3000 });
  await page.evaluate(() => { const track = document.querySelector(".story-track"); const top = track.getBoundingClientRect().top + scrollY; scrollTo({ top: top + (track.offsetHeight - innerHeight) * 0.9, behavior: "instant" }); });
  await page.waitForFunction(() => document.querySelector(".story-panel.is-active")?.textContent?.includes("portfolio"), null, { timeout: 3000 });
  assert(Number(await page.locator(".story-stage").evaluate(element => getComputedStyle(element).getPropertyValue("--story-code-opacity"))) < .1);
  await page.locator(".project-trigger").first().click();
  assert.equal(await page.locator(".project-trigger").first().getAttribute("aria-expanded"), "true");
  assert(await page.locator(".project-detail").first().isVisible());
  await page.locator(".project-trigger").first().click();
  assert.equal(await page.locator(".project-trigger").first().getAttribute("aria-expanded"), "false");
  await page.evaluate(() => { const track = document.querySelector(".work-build-track"); scrollTo({ top: track.getBoundingClientRect().top + scrollY + track.offsetHeight * .42, behavior: "instant" }); });
  await page.waitForFunction(() => { const value = Number(document.querySelector(".work-build-progress")?.getAttribute("aria-valuenow")); return value > 20 && value < 100; });
  const midTrace = await page.locator(".work-command").textContent();
  await page.evaluate(() => { const track = document.querySelector(".work-build-track"); scrollTo({ top: track.getBoundingClientRect().top + scrollY + track.offsetHeight * .67, behavior: "instant" }); });
  await page.waitForFunction(() => document.querySelector(".work-v2-ready") !== null);
  assert.notEqual(await page.locator(".work-command").textContent(), midTrace);
  assert.equal(await page.locator(".work-compiler .script-button").count(), 0);
  assert((await page.locator(".work-compile-control").textContent()).includes("Two projects ready"));
  await page.evaluate(() => { const track = document.querySelector(".work-build-track"); scrollTo({ top: track.getBoundingClientRect().top + scrollY + track.offsetHeight * .35, behavior: "instant" }); });
  await page.waitForFunction(() => Number(document.querySelector(".work-build-progress")?.getAttribute("aria-valuenow")) < 100);
  await page.evaluate(() => { const track = document.querySelector(".work-build-track"); scrollTo({ top: track.getBoundingClientRect().top + scrollY + track.offsetHeight * .67, behavior: "instant" }); });
  await page.waitForFunction(() => document.querySelector(".work-v2-ready") !== null);
  assert.equal(await page.locator(".contact-section .contact-action").getAttribute("href"), "mailto:Adnan.Naous@outlook.com");
  assert(!(await page.locator("#contact").textContent()).includes("Adnan.Naous@outlook.com"));
  assert.equal(await page.locator(".social-name small").count(), 0);
  await page.mouse.move(0, 0);
  await page.locator("#contact").scrollIntoViewIfNeeded();
  await page.locator(".contact-recall").waitFor({ state: "visible", timeout: 16000 });
  assert.equal(await page.locator(".contact-action").count(), 0);
  await page.locator(".contact-recall").click();
  assert.equal(await page.locator(".contact-action").count(), 1);
  assert(await page.locator(".contact-glitch").isVisible());
  assert((await page.locator(".site-footer").textContent()).includes("All rights reserved"));
  assert(await page.locator(".site-footer").evaluate(element => element.getBoundingClientRect().width >= innerWidth - 1));
  assert.equal((await page.request.get(new URL("/documents/adnan-naous-cv.pdf", page.url()).href)).status(), 200);
  await page.evaluate(() => scrollTo(0, 0));
  await page.waitForTimeout(1100);
  assert.notEqual(await page.locator(".visitor-clock strong").textContent(), "00:00");
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  assert.deepEqual(errors, []);
  const startPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await startPage.goto(base);
  assert(await startPage.locator(".intro-retro-screen").evaluate(screen => {
    const bounds = screen.getBoundingClientRect();
    return bounds.left <= 12 && bounds.top <= 12 && bounds.right >= innerWidth - 12 && bounds.bottom >= innerHeight - 12;
  }), "Phone CRT should fill the viewport");
  assert(await startPage.evaluate(() => document.querySelector(".intro-retro-skip").getBoundingClientRect().bottom < document.querySelector(".intro-retro-bottom").getBoundingClientRect().top), "Phone Skip should clear the status line");
  await startPage.locator(".intro-retro-prompt").click();
  await startPage.locator(".intro").waitFor({ state: "hidden" });
  await startPage.locator(".terminal-secret").click();
  await startPage.locator("#terminal-input").click();
  await startPage.waitForTimeout(1500);
  assert.equal(await startPage.evaluate(() => document.activeElement?.id), "terminal-input", "Phone terminal input should keep focus");
  await startPage.setViewportSize({ width: 390, height: 500 });
  assert(await startPage.locator("#terminal-input").evaluate(element => element.getBoundingClientRect().bottom <= innerHeight));
  await startPage.close();
  console.log("PASS: English intro, live scene, interactive terminal, timeline, Codex, story, projects, contact/CV, mobile, no page errors.");
} finally {
  await browser.close();
}
