import assert from "node:assert/strict";
import { chromium } from "playwright";

const base = process.env.BASE_URL || "http://127.0.0.1:3000";
const browser = await chromium.launch({ channel: "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(base);
  assert(await page.locator(".intro-retro-screen").isVisible());
  const fillsViewport = () => page.locator(".intro-retro-screen").evaluate(screen => {
    const bounds = screen.getBoundingClientRect();
    return bounds.left <= 20 && bounds.top <= 20 && bounds.right >= innerWidth - 20 && bounds.bottom >= innerHeight - 20;
  });
  assert(await fillsViewport(), "Desktop CRT should fill the viewport");
  assert(await page.evaluate(() => document.querySelector(".intro-retro-skip").getBoundingClientRect().bottom < document.querySelector(".intro-retro-bottom").getBoundingClientRect().top), "Desktop Skip should clear the status line");
  assert((await page.locator(".intro-retro-name").textContent()).includes("Adnan"));
  await page.waitForFunction(() => ["done", "skip"].includes(document.querySelector(".intro")?.getAttribute("data-state")), { timeout: 7000 });
  await page.locator(".intro").waitFor({ state: "hidden" });
  assert.equal(await page.locator("h1").count(), 1);
  assert.equal(await page.locator(".live-world canvas").count(), 1);
  assert.equal(await page.locator("#home .command-action").count(), 0);
  assert(await page.locator(".hero-terminal").isVisible());
  assert(await page.evaluate(() => document.querySelector(".hero-coordinate").getBoundingClientRect().top > document.querySelector(".hero-terminal").getBoundingClientRect().bottom));
  await page.locator(".terminal-secret").click();
  assert(await page.locator(".terminal-reveal").isVisible());
  assert.equal(await page.locator(".timeline-rail a").count(), 6);
  assert.equal(await page.locator("#codex").count(), 1);
  assert.equal(await page.locator("a[href*='kanz-ai']").count(), 0);
  assert.equal(await page.locator(".site-nav").evaluate(element => getComputedStyle(element).backdropFilter), "none");
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  const phaseAtTop = await page.locator(".tech-script-b output").textContent();
  await page.locator("#now").scrollIntoViewIfNeeded();
  await page.waitForTimeout(200);
  assert.notEqual(await page.locator(".tech-script-b output").textContent(), phaseAtTop);
  assert.equal(await page.locator(".activity-bars i").count(), 10);
  assert.equal(await page.locator(".activity-bars i.is-filled").count(), 7);
  assert.equal(await page.locator(".activity-bars").getAttribute("aria-valuenow"), "70");
  assert.equal(await page.locator(".skill-node").count(), 6);
  await page.locator(".skill-node").nth(4).click();
  assert.equal(await page.locator(".skill-node").nth(4).getAttribute("aria-pressed"), "true");
  assert((await page.locator(".skill-readout").textContent()).includes("AI agents"));
  await page.locator("#codex").scrollIntoViewIfNeeded();
  await page.locator(".codex-menu button").nth(1).click();
  assert.equal(await page.locator(".codex-menu button").nth(1).getAttribute("aria-pressed"), "true");
  assert((await page.locator(".codex-detail-copy").textContent()).includes("useful software"));
  await page.locator("#about").scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  assert.equal(await page.locator(".story-panel").count(), 4);
  assert.equal(await page.locator(".story-controls").count(), 0);
  assert.equal(await page.locator(".story-panel.is-active").count(), 1);
  await page.evaluate(() => { const track = document.querySelector(".story-track"); const top = track.getBoundingClientRect().top + scrollY; scrollTo({ top: top + (track.offsetHeight - innerHeight) * 0.5, behavior: "instant" }); });
  await page.waitForTimeout(150);
  assert((await page.locator(".story-panel.is-active").textContent()).includes("Adnan OS"));
  await page.evaluate(() => { const track = document.querySelector(".story-track"); const top = track.getBoundingClientRect().top + scrollY; scrollTo({ top: top + (track.offsetHeight - innerHeight) * 0.9, behavior: "instant" }); });
  await page.waitForTimeout(150);
  assert((await page.locator(".story-panel.is-active").textContent()).includes("bilingual portfolio"));
  await page.locator(".project-trigger").first().click();
  assert.equal(await page.locator(".project-trigger").first().getAttribute("aria-expanded"), "true");
  assert(await page.locator(".project-detail").first().isVisible());
  await page.locator(".project-trigger").first().click();
  assert.equal(await page.locator(".project-trigger").first().getAttribute("aria-expanded"), "false");
  await page.locator("#work").scrollIntoViewIfNeeded();
  await page.locator(".work-compiler .script-button").click();
  assert(await page.locator(".work-compiler.is-running").count() === 1);
  await page.waitForTimeout(1450);
  assert((await page.locator(".work-compile-control").textContent()).includes("Two records ready"));
  assert.equal(await page.locator(".contact-section .contact-action").getAttribute("href"), "mailto:Adnan.Naous@outlook.com");
  assert.equal(await page.locator(".transmission-foot a").getAttribute("href"), "mailto:Adnan.Naous@outlook.com");
  await page.locator("#contact").scrollIntoViewIfNeeded();
  await page.locator(".contact-recall").waitFor({ state: "visible", timeout: 10000 });
  assert.equal(await page.locator(".contact-action").count(), 0);
  await page.locator(".contact-recall").click();
  assert.equal(await page.locator(".contact-action").count(), 1);
  assert(await page.locator(".contact-glitch").isVisible());
  assert((await page.locator(".site-footer").textContent()).includes("All rights reserved"));
  assert.equal((await page.request.get(new URL("/documents/adnan-naous-cv.pdf", page.url()).href)).status(), 200);
  await page.evaluate(() => scrollTo(0, 0));
  await page.waitForTimeout(750);
  await page.getByRole("button", { name: "Switch to Arabic" }).click();
  assert.equal(await page.locator("html").getAttribute("dir"), "rtl");
  await page.reload();
  assert.equal(await page.locator("html").getAttribute("lang"), "ar");
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  assert.deepEqual(errors, []);
  const startPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await startPage.goto(base);
  assert(await startPage.locator(".intro-retro-screen").evaluate(screen => {
    const bounds = screen.getBoundingClientRect();
    return bounds.left <= 12 && bounds.top <= 12 && bounds.right >= innerWidth - 12 && bounds.bottom >= innerHeight - 12;
  }), "Phone CRT should fill the viewport");
  assert(await startPage.evaluate(() => document.querySelector(".intro-retro-skip").getBoundingClientRect().bottom < document.querySelector(".intro-retro-bottom").getBoundingClientRect().top), "Phone Skip should clear the status line");
  await startPage.locator(".intro-retro-prompt").click();
  await startPage.locator(".intro").waitFor({ state: "hidden" });
  await startPage.close();
  console.log("PASS: intro, live scene, terminal, timeline, Codex, story, projects, contact/CV, Arabic, mobile, no page errors.");
} finally {
  await browser.close();
}
