import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({channel:'chrome'});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:3000');
  await page.evaluate(()=>document.fonts.ready);
  await page.waitForFunction(()=>document.querySelector('.intro')?.getAttribute('data-visible')==='done',{timeout:6000});
  await page.waitForTimeout(1100);
  await page.locator('.galaxy-environment canvas').waitFor({timeout:10000});
  assert.equal(await page.locator('h1').count(),1);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'C:/Users/Adnan Naous/.codex/visualizations/portfolio-glass-desktop.png'});
  await page.locator('.project-open').first().click();
  assert(await page.locator('dialog').evaluate(el=>el.open));
  await page.keyboard.press('Escape');
  assert(!(await page.locator('dialog').evaluate(el=>el.open)));
  await page.getByRole('button',{name:'Switch to Arabic'}).click();
  assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>scrollTo(0,0));
  await page.waitForTimeout(500);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:'C:/Users/Adnan Naous/.codex/visualizations/portfolio-glass-mobile.png'});
  await page.locator('.dock a[href="#contact"]').click();
  await page.waitForTimeout(1200);
  await page.locator('#contact').screenshot({path:'C:/Users/Adnan Naous/.codex/visualizations/portfolio-glass-contact.png'});
  await page.locator('#work').scrollIntoViewIfNeeded();
  await page.waitForTimeout(1200);
  await page.locator('#work').screenshot({path:'C:/Users/Adnan Naous/.codex/visualizations/portfolio-glass-work.png'});
  assert.equal(await page.locator('.contact-button').getAttribute('href'),'mailto:Adnan.Naous@outlook.com');
  assert.equal((await page.request.get(new URL('/documents/adnan-naous-cv.pdf',page.url()).href)).status(),200);
  await page.locator('.project-open').last().click();
  assert(await page.locator('dialog').evaluate(el=>el.open));
  await page.keyboard.press('Escape');
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('lang'),'ar');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.galaxy-environment canvas').count(),1);
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile, RTL persistence, project dialogs, email link, CV, reduced motion, no page errors.');
} finally {await browser.close();}
